// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqBYQ_iRyEn8vqTkUr49el6PRnMyPQ_yI',
    appId: '1:387854887613:web:a5c4904d7edeb70eea65d4',
    messagingSenderId: '387854887613',
    projectId: 'pchub-c355b',
    authDomain: 'pchub-c355b.firebaseapp.com',
    storageBucket: 'pchub-c355b.firebasestorage.app',
    measurementId: 'G-ZYQN8P2N19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlRRb6Z3stAiFMcm1e_zOwN_VO2xgJWXc',
    appId: '1:387854887613:android:62be5a856371052cea65d4',
    messagingSenderId: '387854887613',
    projectId: 'pchub-c355b',
    storageBucket: 'pchub-c355b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVzBQTkVYSsuanXcMtpdCZ_e0UdiM6bA',
    appId: '1:387854887613:ios:72f3bfefc20ac47cea65d4',
    messagingSenderId: '387854887613',
    projectId: 'pchub-c355b',
    storageBucket: 'pchub-c355b.firebasestorage.app',
    iosBundleId: 'com.example.pcHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlVzBQTkVYSsuanXcMtpdCZ_e0UdiM6bA',
    appId: '1:387854887613:ios:72f3bfefc20ac47cea65d4',
    messagingSenderId: '387854887613',
    projectId: 'pchub-c355b',
    storageBucket: 'pchub-c355b.firebasestorage.app',
    iosBundleId: 'com.example.pcHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqBYQ_iRyEn8vqTkUr49el6PRnMyPQ_yI',
    appId: '1:387854887613:web:197b22b1786a3351ea65d4',
    messagingSenderId: '387854887613',
    projectId: 'pchub-c355b',
    authDomain: 'pchub-c355b.firebaseapp.com',
    storageBucket: 'pchub-c355b.firebasestorage.app',
    measurementId: 'G-N9B88LYNNM',
  );
}
